# Generated by Django 2.2.1 on 2019-05-22 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='noimage.jpg', upload_to='post_images'),
        ),
    ]
